:toc:
:toc-placement!:
:toclevels: 3
= Wi-Fi Control

_Wi-Fi Control_ is an Android app that allows controlling services in the local network via the smartphone.

toc::[]

== Synopsis
Wi-Fi Control targets hobbyists and SmartHome enthusiasts who run services (such as IoT applications or media servers) in their home network. A _service_ in this context is an application running on a computer reachable via the Wi-Fi. For interaction, the application exposes a control UI on a defined URL. Wi-Fi Control can be used to manage such services by creating corresponding service definitions in the app. It then accesses the services via their URLs and opens their control UIs in a Web view control. That way, users can interact with these services via their smartphone; it is not necessary that the computers running the services are connected to input or output devices like a keyboard or a monitor.

The URL of a service can either be fix; in this case it can be hard-coded in the service definition. Alternatively, an auto-discovery mechanism is available. Wi-Fi Control then tries to discover the service URL automatically using a proprietary protocol based on https://en.wikipedia.org/wiki/User_Datagram_Protocol[UDP] requests. This is especially useful if https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol[DHCP] is used, and IP addresses or URLs can change dynamically.

The original use case for this app was an audio player application running on a https://www.raspberrypi.com/[Raspberry Pi]. The tiny computer should be placed somewhere in the background where no space was available for a screen or a keyboard. So, how could users interact with the player software? The solution was to expose the player functionality via a Web UI which could be used from a smartphone.

Since there are many possible scenarios with similar requirements, Wi-Fi Control has been developed to handle them in a generic way.
