[versions]
androidApplicationPlugin = "8.1.0"
androidLibraryPlugin = "8.1.0"
kotlinAndroidPlugin = "1.8.21"

activityCompose = "1.7.2"
composeMaterial = "1.4.3"
composeUi = "1.4.3"
coreKtx = "1.9.0"
coroutines = "1.7.1"
junit = "4.13.2"
junitVintage = "5.9.3"
koTest = "5.6.2"
lifecycleRuntimeKtx = "2.6.1"
mockk = "1.13.5"
robolectric = "4.10.3"
testEspresso = "3.5.1"
testJUnit = "1.1.5"
webView = "0.31.3-beta"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplicationPlugin" }
android-library = { id = "com.android.library", version.ref = "androidLibraryPlugin" }
kotlin-android = { id= "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidPlugin" }

[libraries]
accompanist-webview = { group = "com.google.accompanist", name = "accompanist-webview", version.ref = "webView" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeMaterial" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeUi" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeUi" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeUi" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeUi" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeUi" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "testEspresso" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "testJUnit" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junitVintage = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junitVintage" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "koTest" }
kotest-runner-junit = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "koTest" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
